name: Frontend Cache Dependencies

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - uses: actions/checkout@v4

      - name: Cache Node.js Modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies on Cache Miss
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci
