name: Python Cache Dependencies

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    defaults:
      run:
        working-directory: farcaster  # Set the default working directory for all steps

    steps:
      - uses: actions/checkout@v4

      - name: Cache Python Dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install Dependencies on Cache Miss
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt
